python3 -u -m DiscoverMotorPrograms.Experiments.abstraction.mime --display_freq=5000 -optim_bs=2 --variable_ns=False --num_pretrain_skillnet_epoch=100 --fixed_skillnet --nz=64 --nh=64 --MIME_dir=/checkpoint/tanmayshankar/MIME/ --variable_nseg --num_epochs=300 --lr_step_epoch_freq=50 --name=T163_vnseg_sl1pt0_pcont0pt5_fakefnseg --lpred_p_bias=0 --len_loss_wt=0.01 --step_loss_wt=1.0 --align_loss_wt=0.1 --transformer --nonormalize_loss --checkpoint_dir=saved_models/ --pretrain_skillnet_name=mime_plan_ba_fns_64 --lpred_p_bias=0.5 --st_space=joint_both --num_pretrain_epochs=-1 --network_dir=saved_models/T163_vnseg_sl1pt0_pcont0pt5_fakefnseg

# MIME Plan skill net
python cluster_run.py --name=M1_NewMIMESkillNet --partition=learnfair --cmd='python -m DiscoverMotorPrograms.Experiments.abstraction.mime_plan_skill --plot_scalars --display_visuals=True --display_freq=5000 --name=M1_NewMIMESkillNet --st_space=joint_both --MIME_dir=/checkpoint/tanmayshankar/MIME/ --num_epochs=100 --lr_step_epoch_freq=50 --optim_bs=2 --variable_ns=False --gpu_id=0 --align_loss_wt=1.0 --nz=64 --nh=64 --pred_gripper=True'

# python -m DiscoverMotorPrograms.Experiments.abstraction.mime_plan_skill --plot_scalars --display_visuals=True --display_freq=5000 --name=M2_NewMIMESkillNet --st_space=joint_both --MIME_dir=/checkpoint/tanmayshankar/MIME/ --num_epochs=100 --lr_step_epoch_freq=50 --optim_bs=2 --variable_ns=False --gpu_id=0 --align_loss_wt=1.0 --nz=64 --nh=64 --pred_gripper=True

# Run VAE version of skill net. 
python cluster_run.py --name=M3_NewMIMESkillNet_VAE --partition=learnfair --cmd='python -m DiscoverMotorPrograms.Experiments.abstraction.mime_plan_skill --plot_scalars --display_visuals=True --display_freq=5000 --name=M3_NewMIMESkillNet_VAE --st_space=joint_both --MIME_dir=/checkpoint/tanmayshankar/MIME/ --num_epochs=100 --lr_step_epoch_freq=50 --optim_bs=2 --variable_ns=False --gpu_id=0 --align_loss_wt=1.0 --nz=64 --nh=64 --pred_gripper=True --vae_enc=True'

# Running VNSeg with two tricks: 
# 1) FNSeg for few epochs with number set to 4. 
# 2) Probability multiplication bias. 
python3 -u -m DiscoverMotorPrograms.Experiments.abstraction.mime --display_freq=5000 -optim_bs=2 --variable_ns=False --num_pretrain_skillnet_epoch=100 --fixed_skillnet --nz=64 --nh=64 --MIME_dir=/checkpoint/tanmayshankar/MIME/ --variable_nseg --num_epochs=300 --lr_step_epoch_freq=50 --name=M4_NewMIMEVNSeg_n4 --lpred_p_bias=0 --len_loss_wt=0.01 --step_loss_wt=2. --align_loss_wt=0.1 --transformer --nonormalize_loss --checkpoint_dir=saved_models/ --pretrain_skillnet_name=M1_NewMIMESkillNet --lpred_p_bias=0.5 --b_probability_factor=0.01 --st_space=joint_both_gripper --n_skill_segments=4

python3 -u -m DiscoverMotorPrograms.Experiments.abstraction.mime --display_freq=5000 -optim_bs=2 --variable_ns=False --num_pretrain_skillnet_epoch=100 --fixed_skillnet --nz=64 --nh=64 --MIME_dir=/checkpoint/tanmayshankar/MIME/ --variable_nseg --num_epochs=300 --lr_step_epoch_freq=50 --name=M5_NewMIMEVNSeg_n6 --lpred_p_bias=0 --len_loss_wt=0.01 --step_loss_wt=2. --align_loss_wt=0.1 --transformer --nonormalize_loss --checkpoint_dir=saved_models/ --pretrain_skillnet_name=M1_NewMIMESkillNet --lpred_p_bias=0.5 --b_probability_factor=0.01 --st_space=joint_both_gripper --n_skill_segments=6

# Profiling code. 
python3 -u -m DiscoverMotorPrograms.Experiments.abstraction.mime --display_freq=5000 -optim_bs=2 --variable_ns=False --num_pretrain_skillnet_epoch=100 --fixed_skillnet --nz=64 --nh=64 --MIME_dir=/checkpoint/tanmayshankar/MIME/ --variable_nseg --num_epochs=300 --lr_step_epoch_freq=50 --name=M6Profile_NewMIMEVNSeg_n6 --lpred_p_bias=0 --len_loss_wt=0.01 --step_loss_wt=2. --align_loss_wt=0.1 --transformer --nonormalize_loss --checkpoint_dir=saved_models/ --pretrain_skillnet_name=M1_NewMIMESkillNet --lpred_p_bias=0.5 --b_probability_factor=0.01 --st_space=joint_both_gripper --n_skill_segments=6

##### Load M20 from previous
python cluster_run.py --name=M7 --partition=priority --cmd='python3 -u -m DiscoverMotorPrograms.Experiments.abstraction.mime --display_freq=5000 -optim_bs=2 --variable_ns=False --num_pretrain_skillnet_epoch=100 --fixed_skillnet --nz=64 --nh=64 --MIME_dir=/checkpoint/tanmayshankar/MIME/ --variable_nseg --num_epochs=300 --lr_step_epoch_freq=50 --name=M7_NewMIMEVNSeg_n4_loadM4m20_b1pt0 --len_loss_wt=0.01 --step_loss_wt=2. --align_loss_wt=0.1 --transformer --nonormalize_loss --checkpoint_dir=saved_models/ --pretrain_skillnet_name=M1_NewMIMESkillNet --lpred_p_bias=1. --b_probability_factor=0.01 --st_space=joint_both_gripper --n_skill_segments=4 --network_dir=saved_models/M4_NewMIMEVNSeg_n4/ --num_pretrain_epochs=20 --presoftmax_bias=True'

python cluster_run.py --name=M8 --partition=priority --cmd='python3 -u -m DiscoverMotorPrograms.Experiments.abstraction.mime --display_freq=5000 -optim_bs=2 --variable_ns=False --num_pretrain_skillnet_epoch=100 --fixed_skillnet --nz=64 --nh=64 --MIME_dir=/checkpoint/tanmayshankar/MIME/ --variable_nseg --num_epochs=300 --lr_step_epoch_freq=50 --name=M8_NewMIMEVNSeg_n4_loadM4m20_b2pt0 --len_loss_wt=0.01 --step_loss_wt=2. --align_loss_wt=0.1 --transformer --nonormalize_loss --checkpoint_dir=saved_models/ --pretrain_skillnet_name=M1_NewMIMESkillNet --lpred_p_bias=2. --b_probability_factor=0.01 --st_space=joint_both_gripper --n_skill_segments=4 --network_dir=saved_models/M4_NewMIMEVNSeg_n4/ --num_pretrain_epochs=20 --presoftmax_bias=True'

python cluster_run.py --name=M9 --partition=priority --cmd='python3 -u -m DiscoverMotorPrograms.Experiments.abstraction.mime --display_freq=5000 -optim_bs=2 --variable_ns=False --num_pretrain_skillnet_epoch=100 --fixed_skillnet --nz=64 --nh=64 --MIME_dir=/checkpoint/tanmayshankar/MIME/ --variable_nseg --num_epochs=300 --lr_step_epoch_freq=50 --name=M9_NewMIMEVNSeg_n4_loadM4m20_b3pt0 --len_loss_wt=0.01 --step_loss_wt=2. --align_loss_wt=0.1 --transformer --nonormalize_loss --checkpoint_dir=saved_models/ --pretrain_skillnet_name=M1_NewMIMESkillNet --lpred_p_bias=3. --b_probability_factor=0.01 --st_space=joint_both_gripper --n_skill_segments=4 --network_dir=saved_models/M4_NewMIMEVNSeg_n4/ --num_pretrain_epochs=20 --presoftmax_bias=True'

python cluster_run.py --name=M10 --partition=priority --cmd='python3 -u -m DiscoverMotorPrograms.Experiments.abstraction.mime --display_freq=5000 -optim_bs=2 --variable_ns=False --num_pretrain_skillnet_epoch=100 --fixed_skillnet --nz=64 --nh=64 --MIME_dir=/checkpoint/tanmayshankar/MIME/ --variable_nseg --num_epochs=300 --lr_step_epoch_freq=50 --name=M10_NewMIMEVNSeg_n4_loadM4m20_b5pt0 --len_loss_wt=0.01 --step_loss_wt=2. --align_loss_wt=0.1 --transformer --nonormalize_loss --checkpoint_dir=saved_models/ --pretrain_skillnet_name=M1_NewMIMESkillNet --lpred_p_bias=5. --b_probability_factor=0.01 --st_space=joint_both_gripper --n_skill_segments=4 --network_dir=saved_models/M4_NewMIMEVNSeg_n4/ --num_pretrain_epochs=20 --presoftmax_bias=True'


python cluster_run.py --name=M11 --partition=priority --cmd='python3 -u -m DiscoverMotorPrograms.Experiments.abstraction.mime --display_freq=5000 -optim_bs=2 --variable_ns=False --num_pretrain_skillnet_epoch=100 --fixed_skillnet --nz=64 --nh=64 --MIME_dir=/checkpoint/tanmayshankar/MIME/ --variable_nseg --num_epochs=300 --lr_step_epoch_freq=50 --name=M11_NewMIMEVNSeg_n6_loadM5m20_b1pt0 --len_loss_wt=0.01 --step_loss_wt=2. --align_loss_wt=0.1 --transformer --nonormalize_loss --checkpoint_dir=saved_models/ --pretrain_skillnet_name=M1_NewMIMESkillNet --lpred_p_bias=1. --b_probability_factor=0.01 --st_space=joint_both_gripper --n_skill_segments=6 --network_dir=saved_models/M5_NewMIMEVNSeg_n6/ --num_pretrain_epochs=20 --presoftmax_bias=True'

python cluster_run.py --name=M12 --partition=priority --cmd='python3 -u -m DiscoverMotorPrograms.Experiments.abstraction.mime --display_freq=5000 -optim_bs=2 --variable_ns=False --num_pretrain_skillnet_epoch=100 --fixed_skillnet --nz=64 --nh=64 --MIME_dir=/checkpoint/tanmayshankar/MIME/ --variable_nseg --num_epochs=300 --lr_step_epoch_freq=50 --name=M12_NewMIMEVNSeg_n6_loadM5m20_b2pt0 --len_loss_wt=0.01 --step_loss_wt=2. --align_loss_wt=0.1 --transformer --nonormalize_loss --checkpoint_dir=saved_models/ --pretrain_skillnet_name=M1_NewMIMESkillNet --lpred_p_bias=2. --b_probability_factor=0.01 --st_space=joint_both_gripper --n_skill_segments=6 --network_dir=saved_models/M5_NewMIMEVNSeg_n6/ --num_pretrain_epochs=20 --presoftmax_bias=True'

python cluster_run.py --name=M13 --partition=priority --cmd='python3 -u -m DiscoverMotorPrograms.Experiments.abstraction.mime --display_freq=5000 -optim_bs=2 --variable_ns=False --num_pretrain_skillnet_epoch=100 --fixed_skillnet --nz=64 --nh=64 --MIME_dir=/checkpoint/tanmayshankar/MIME/ --variable_nseg --num_epochs=300 --lr_step_epoch_freq=50 --name=M13_NewMIMEVNSeg_n6_loadM5m20_b3pt0 --len_loss_wt=0.01 --step_loss_wt=2. --align_loss_wt=0.1 --transformer --nonormalize_loss --checkpoint_dir=saved_models/ --pretrain_skillnet_name=M1_NewMIMESkillNet --lpred_p_bias=3. --b_probability_factor=0.01 --st_space=joint_both_gripper --n_skill_segments=6 --network_dir=saved_models/M5_NewMIMEVNSeg_n6/ --num_pretrain_epochs=20 --presoftmax_bias=True'

python cluster_run.py --name=M14 --partition=priority --cmd='python3 -u -m DiscoverMotorPrograms.Experiments.abstraction.mime --display_freq=5000 -optim_bs=2 --variable_ns=False --num_pretrain_skillnet_epoch=100 --fixed_skillnet --nz=64 --nh=64 --MIME_dir=/checkpoint/tanmayshankar/MIME/ --variable_nseg --num_epochs=300 --lr_step_epoch_freq=50 --name=M14_NewMIMEVNSeg_n6_loadM5m20_b5pt0 --len_loss_wt=0.01 --step_loss_wt=2. --align_loss_wt=0.1 --transformer --nonormalize_loss --checkpoint_dir=saved_models/ --pretrain_skillnet_name=M1_NewMIMESkillNet --lpred_p_bias=5. --b_probability_factor=0.01 --st_space=joint_both_gripper --n_skill_segments=6 --network_dir=saved_models/M5_NewMIMEVNSeg_n6/ --num_pretrain_epochs=20 --presoftmax_bias=True'

# Run again with randomized data and properly set skills. 
python cluster_run.py --name=M15 --partition=priority --cmd='python3 -u -m DiscoverMotorPrograms.Experiments.abstraction.mime --display_freq=5000 -optim_bs=2 --variable_ns=False --num_pretrain_skillnet_epoch=100 --fixed_skillnet --nz=64 --nh=64 --MIME_dir=/checkpoint/tanmayshankar/MIME/ --variable_nseg --num_epochs=300 --lr_step_epoch_freq=50 --name=M15_NewMIMEVNSeg_n4_loadM4m20_b1pt0 --len_loss_wt=0.01 --step_loss_wt=2. --align_loss_wt=0.1 --transformer --nonormalize_loss --checkpoint_dir=saved_models/ --pretrain_skillnet_name=M1_NewMIMESkillNet --lpred_p_bias=1. --b_probability_factor=0.01 --st_space=joint_both_gripper --n_skill_segments=4 --network_dir=saved_models/M4_NewMIMEVNSeg_n4/ --num_pretrain_epochs=20 --presoftmax_bias=True'

python cluster_run.py --name=M16 --partition=priority --cmd='python3 -u -m DiscoverMotorPrograms.Experiments.abstraction.mime --display_freq=5000 -optim_bs=2 --variable_ns=False --num_pretrain_skillnet_epoch=100 --fixed_skillnet --nz=64 --nh=64 --MIME_dir=/checkpoint/tanmayshankar/MIME/ --variable_nseg --num_epochs=300 --lr_step_epoch_freq=50 --name=M16_NewMIMEVNSeg_n4_loadM4m20_b1pt5 --len_loss_wt=0.01 --step_loss_wt=2. --align_loss_wt=0.1 --transformer --nonormalize_loss --checkpoint_dir=saved_models/ --pretrain_skillnet_name=M1_NewMIMESkillNet --lpred_p_bias=1.5 --b_probability_factor=0.01 --st_space=joint_both_gripper --n_skill_segments=4 --network_dir=saved_models/M4_NewMIMEVNSeg_n4/ --num_pretrain_epochs=20 --presoftmax_bias=True'

python cluster_run.py --name=M17 --partition=priority --cmd='python3 -u -m DiscoverMotorPrograms.Experiments.abstraction.mime --display_freq=5000 -optim_bs=2 --variable_ns=False --num_pretrain_skillnet_epoch=100 --fixed_skillnet --nz=64 --nh=64 --MIME_dir=/checkpoint/tanmayshankar/MIME/ --variable_nseg --num_epochs=300 --lr_step_epoch_freq=50 --name=M17_NewMIMEVNSeg_n4_loadM4m20_b2pt0 --len_loss_wt=0.01 --step_loss_wt=2. --align_loss_wt=0.1 --transformer --nonormalize_loss --checkpoint_dir=saved_models/ --pretrain_skillnet_name=M1_NewMIMESkillNet --lpred_p_bias=2. --b_probability_factor=0.01 --st_space=joint_both_gripper --n_skill_segments=4 --network_dir=saved_models/M4_NewMIMEVNSeg_n4/ --num_pretrain_epochs=20 --presoftmax_bias=True'

python cluster_run.py --name=M18 --partition=priority --cmd='python3 -u -m DiscoverMotorPrograms.Experiments.abstraction.mime --display_freq=5000 -optim_bs=2 --variable_ns=False --num_pretrain_skillnet_epoch=100 --fixed_skillnet --nz=64 --nh=64 --MIME_dir=/checkpoint/tanmayshankar/MIME/ --variable_nseg --num_epochs=300 --lr_step_epoch_freq=50 --name=M18_NewMIMEVNSeg_n4_loadM4m20_b3pt0 --len_loss_wt=0.01 --step_loss_wt=2. --align_loss_wt=0.1 --transformer --nonormalize_loss --checkpoint_dir=saved_models/ --pretrain_skillnet_name=M1_NewMIMESkillNet --lpred_p_bias=3. --b_probability_factor=0.01 --st_space=joint_both_gripper --n_skill_segments=4 --network_dir=saved_models/M4_NewMIMEVNSeg_n4/ --num_pretrain_epochs=20 --presoftmax_bias=True'

python cluster_run.py --name=M19 --partition=priority --cmd='python3 -u -m DiscoverMotorPrograms.Experiments.abstraction.mime --display_freq=5000 -optim_bs=2 --variable_ns=False --num_pretrain_skillnet_epoch=100 --fixed_skillnet --nz=64 --nh=64 --MIME_dir=/checkpoint/tanmayshankar/MIME/ --variable_nseg --num_epochs=300 --lr_step_epoch_freq=50 --name=M19_NewMIMEVNSeg_n6_loadM5m20_b1pt0 --len_loss_wt=0.01 --step_loss_wt=2. --align_loss_wt=0.1 --transformer --nonormalize_loss --checkpoint_dir=saved_models/ --pretrain_skillnet_name=M1_NewMIMESkillNet --lpred_p_bias=1. --b_probability_factor=0.01 --st_space=joint_both_gripper --n_skill_segments=6 --network_dir=saved_models/M5_NewMIMEVNSeg_n6/ --num_pretrain_epochs=20 --presoftmax_bias=True'

python cluster_run.py --name=M20 --partition=priority --cmd='python3 -u -m DiscoverMotorPrograms.Experiments.abstraction.mime --display_freq=5000 -optim_bs=2 --variable_ns=False --num_pretrain_skillnet_epoch=100 --fixed_skillnet --nz=64 --nh=64 --MIME_dir=/checkpoint/tanmayshankar/MIME/ --variable_nseg --num_epochs=300 --lr_step_epoch_freq=50 --name=M20_NewMIMEVNSeg_n6_loadM5m20_b1pt5 --len_loss_wt=0.01 --step_loss_wt=2. --align_loss_wt=0.1 --transformer --nonormalize_loss --checkpoint_dir=saved_models/ --pretrain_skillnet_name=M1_NewMIMESkillNet --lpred_p_bias=1.5 --b_probability_factor=0.01 --st_space=joint_both_gripper --n_skill_segments=6 --network_dir=saved_models/M5_NewMIMEVNSeg_n6/ --num_pretrain_epochs=20 --presoftmax_bias=True'

python cluster_run.py --name=M21 --partition=priority --cmd='python3 -u -m DiscoverMotorPrograms.Experiments.abstraction.mime --display_freq=5000 -optim_bs=2 --variable_ns=False --num_pretrain_skillnet_epoch=100 --fixed_skillnet --nz=64 --nh=64 --MIME_dir=/checkpoint/tanmayshankar/MIME/ --variable_nseg --num_epochs=300 --lr_step_epoch_freq=50 --name=M21_NewMIMEVNSeg_n6_loadM5m20_b2pt0 --len_loss_wt=0.01 --step_loss_wt=2. --align_loss_wt=0.1 --transformer --nonormalize_loss --checkpoint_dir=saved_models/ --pretrain_skillnet_name=M1_NewMIMESkillNet --lpred_p_bias=2. --b_probability_factor=0.01 --st_space=joint_both_gripper --n_skill_segments=6 --network_dir=saved_models/M5_NewMIMEVNSeg_n6/ --num_pretrain_epochs=20 --presoftmax_bias=True'

python cluster_run.py --name=M22 --partition=priority --cmd='python3 -u -m DiscoverMotorPrograms.Experiments.abstraction.mime --display_freq=5000 -optim_bs=2 --variable_ns=False --num_pretrain_skillnet_epoch=100 --fixed_skillnet --nz=64 --nh=64 --MIME_dir=/checkpoint/tanmayshankar/MIME/ --variable_nseg --num_epochs=300 --lr_step_epoch_freq=50 --name=M22_NewMIMEVNSeg_n6_loadM5m20_b3pt0 --len_loss_wt=0.01 --step_loss_wt=2. --align_loss_wt=0.1 --transformer --nonormalize_loss --checkpoint_dir=saved_models/ --pretrain_skillnet_name=M1_NewMIMESkillNet --lpred_p_bias=3. --b_probability_factor=0.01 --st_space=joint_both_gripper --n_skill_segments=6 --network_dir=saved_models/M5_NewMIMEVNSeg_n6/ --num_pretrain_epochs=20 --presoftmax_bias=True'


# Runs without FNSeg
python cluster_run.py --name=M23 --partition=priority --cmd='python3 -u -m DiscoverMotorPrograms.Experiments.abstraction.mime --display_freq=5000 -optim_bs=2 --variable_ns=False --num_pretrain_skillnet_epoch=100 --fixed_skillnet --nz=64 --nh=64 --MIME_dir=/checkpoint/tanmayshankar/MIME/ --variable_nseg --num_epochs=300 --lr_step_epoch_freq=50 --name=M23_NewMIMEVNSeg_n4_loadM4m20_b1pt5 --len_loss_wt=0.01 --step_loss_wt=2. --align_loss_wt=0.1 --transformer --nonormalize_loss --checkpoint_dir=saved_models/ --pretrain_skillnet_name=M1_NewMIMESkillNet --lpred_p_bias=1.5 --b_probability_factor=0.01 --st_space=joint_both_gripper --n_skill_segments=4 --network_dir=saved_models/M4_NewMIMEVNSeg_n4/ --num_pretrain_epochs=20 --presoftmax_bias=True'

python cluster_run.py --name=M24 --partition=priority --cmd='python3 -u -m DiscoverMotorPrograms.Experiments.abstraction.mime --display_freq=5000 -optim_bs=2 --variable_ns=False --num_pretrain_skillnet_epoch=100 --fixed_skillnet --nz=64 --nh=64 --MIME_dir=/checkpoint/tanmayshankar/MIME/ --variable_nseg --num_epochs=300 --lr_step_epoch_freq=50 --name=M24_NewMIMEVNSeg_n4_loadM4m20_b2pt0 --len_loss_wt=0.01 --step_loss_wt=2. --align_loss_wt=0.1 --transformer --nonormalize_loss --checkpoint_dir=saved_models/ --pretrain_skillnet_name=M1_NewMIMESkillNet --lpred_p_bias=2. --b_probability_factor=0.01 --st_space=joint_both_gripper --n_skill_segments=4 --network_dir=saved_models/M4_NewMIMEVNSeg_n4/ --num_pretrain_epochs=20 --presoftmax_bias=True'

python cluster_run.py --name=M25 --partition=priority --cmd='python3 -u -m DiscoverMotorPrograms.Experiments.abstraction.mime --display_freq=5000 -optim_bs=2 --variable_ns=False --num_pretrain_skillnet_epoch=100 --fixed_skillnet --nz=64 --nh=64 --MIME_dir=/checkpoint/tanmayshankar/MIME/ --variable_nseg --num_epochs=300 --lr_step_epoch_freq=50 --name=M25_NewMIMEVNSeg_n6_loadM5m20_b1pt5 --len_loss_wt=0.01 --step_loss_wt=2. --align_loss_wt=0.1 --transformer --nonormalize_loss --checkpoint_dir=saved_models/ --pretrain_skillnet_name=M1_NewMIMESkillNet --lpred_p_bias=1.5 --b_probability_factor=0.01 --st_space=joint_both_gripper --n_skill_segments=6 --network_dir=saved_models/M5_NewMIMEVNSeg_n6/ --num_pretrain_epochs=20 --presoftmax_bias=True'

python cluster_run.py --name=M26 --partition=priority --cmd='python3 -u -m DiscoverMotorPrograms.Experiments.abstraction.mime --display_freq=5000 -optim_bs=2 --variable_ns=False --num_pretrain_skillnet_epoch=100 --fixed_skillnet --nz=64 --nh=64 --MIME_dir=/checkpoint/tanmayshankar/MIME/ --variable_nseg --num_epochs=300 --lr_step_epoch_freq=50 --name=M26_NewMIMEVNSeg_n6_loadM5m20_b2pt0 --len_loss_wt=0.01 --step_loss_wt=2. --align_loss_wt=0.1 --transformer --nonormalize_loss --checkpoint_dir=saved_models/ --pretrain_skillnet_name=M1_NewMIMESkillNet --lpred_p_bias=2. --b_probability_factor=0.01 --st_space=joint_both_gripper --n_skill_segments=6 --network_dir=saved_models/M5_NewMIMEVNSeg_n6/ --num_pretrain_epochs=20 --presoftmax_bias=True'

# Checking the trained models, running with finetuning skill net. 


# Rerun..... 
python cluster_run.py --name=M26 --partition=priority --cmd='python3 -u -m DiscoverMotorPrograms.Experiments.abstraction.mime --display_freq=5000 -optim_bs=2 --variable_ns=False --num_pretrain_skillnet_epoch=100 --fixed_skillnet --nz=64 --nh=64 --MIME_dir=/checkpoint/tanmayshankar/MIME/ --variable_nseg --num_epochs=300 --lr_step_epoch_freq=50 --name=M26_NewMIMEVNSeg_n6_loadM5m20_b2pt0 --len_loss_wt=0.01 --step_loss_wt=2. --align_loss_wt=0.1 --transformer --nonormalize_loss --checkpoint_dir=saved_models/ --pretrain_skillnet_name=M1_NewMIMESkillNet --lpred_p_bias=2. --b_probability_factor=0.01 --st_space=joint_both_gripper --n_skill_segments=6 --network_dir=saved_models/M5_NewMIMEVNSeg_n6/ --num_pretrain_epochs=20 --presoftmax_bias=True'

# Debugz
python3 -u -m DiscoverMotorPrograms.Experiments.abstraction.mime --display_freq=5000 -optim_bs=2 --variable_ns=False --num_pretrain_skillnet_epoch=100 --fixed_skillnet --nz=64 --nh=64 --MIME_dir=/checkpoint/tanmayshankar/MIME/ --variable_nseg --num_epochs=300 --lr_step_epoch_freq=50 --name=M26_NewMIMEVNSeg_n6_loadM5m20_b2pt0 --len_loss_wt=0.01 --step_loss_wt=2. --align_loss_wt=0.1 --transformer --nonormalize_loss --checkpoint_dir=saved_models/ --pretrain_skillnet_name=M1_NewMIMESkillNet --lpred_p_bias=2. --b_probability_factor=0.01 --st_space=joint_both_gripper --n_skill_segments=6 --network_dir=saved_models/M5_NewMIMEVNSeg_n6/ --num_pretrain_epochs=20 --presoftmax_bias=True